///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyCRM.Recordings.Company.SN_001
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyPageLabelDisplayed recording.
    /// </summary>
    [TestModule("da2425a4-869c-4b46-9570-ff4f5752d122", ModuleType.Recording, 1)]
    public partial class VerifyPageLabelDisplayed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MyCRM.MyCRMRepository repository.
        /// </summary>
        public static global::MyCRM.MyCRMRepository repo = global::MyCRM.MyCRMRepository.Instance;

        static VerifyPageLabelDisplayed instance = new VerifyPageLabelDisplayed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyPageLabelDisplayed()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyPageLabelDisplayed Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyCRM.Navigation.Company' at Center.", repo.MyCRM.Navigation.CompanyInfo, new RecordItemIndex(0));
            repo.MyCRM.Navigation.Company.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyCRM.Company.LabelAddLine1'.", repo.MyCRM.Company.LabelAddLine1Info, new RecordItemIndex(1));
            Validate.Exists(repo.MyCRM.Company.LabelAddLine1Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyCRM.Company.LabelAddLine2'.", repo.MyCRM.Company.LabelAddLine2Info, new RecordItemIndex(2));
            Validate.Exists(repo.MyCRM.Company.LabelAddLine2Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyCRM.Company.LabelCity'.", repo.MyCRM.Company.LabelCityInfo, new RecordItemIndex(3));
            Validate.Exists(repo.MyCRM.Company.LabelCityInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyCRM.Company.LabelState'.", repo.MyCRM.Company.LabelStateInfo, new RecordItemIndex(4));
            Validate.Exists(repo.MyCRM.Company.LabelStateInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyCRM.Company.LabelZip'.", repo.MyCRM.Company.LabelZipInfo, new RecordItemIndex(5));
            Validate.Exists(repo.MyCRM.Company.LabelZipInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyCRM.Company.LabeMain'.", repo.MyCRM.Company.LabeMainInfo, new RecordItemIndex(6));
            Validate.Exists(repo.MyCRM.Company.LabeMainInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyCRM.Company.LabelOther'.", repo.MyCRM.Company.LabelOtherInfo, new RecordItemIndex(7));
            Validate.Exists(repo.MyCRM.Company.LabelOtherInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyCRM.Company.CommentBox'.", repo.MyCRM.Company.CommentBoxInfo, new RecordItemIndex(8));
            Validate.Exists(repo.MyCRM.Company.CommentBoxInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
