///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyCRM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyCRMRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("320422cc-3ab0-40a5-848a-96c127c13395")]
    public partial class MyCRMRepository : RepoGenBaseFolder
    {
        static MyCRMRepository instance = new MyCRMRepository();
        MyCRMRepositoryFolders.MyCRMAppFolder _mycrm;

        /// <summary>
        /// Gets the singleton class instance representing the MyCRMRepository element repository.
        /// </summary>
        [RepositoryFolder("320422cc-3ab0-40a5-848a-96c127c13395")]
        public static MyCRMRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyCRMRepository() 
            : base("MyCRMRepository", "/", null, 0, false, "320422cc-3ab0-40a5-848a-96c127c13395", ".\\RepositoryImages\\MyCRMRepository320422cc.rximgres")
        {
            _mycrm = new MyCRMRepositoryFolders.MyCRMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("320422cc-3ab0-40a5-848a-96c127c13395")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MyCRM folder.
        /// </summary>
        [RepositoryFolder("49c06412-954f-4f86-8daa-ddc85200f715")]
        public virtual MyCRMRepositoryFolders.MyCRMAppFolder MyCRM
        {
            get { return _mycrm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyCRMRepositoryFolders
    {
        /// <summary>
        /// The MyCRMAppFolder folder.
        /// </summary>
        [RepositoryFolder("49c06412-954f-4f86-8daa-ddc85200f715")]
        public partial class MyCRMAppFolder : RepoGenBaseFolder
        {
            MyCRMRepositoryFolders.PeopleFolder _people;
            MyCRMRepositoryFolders.CompanyFolder _company;
            MyCRMRepositoryFolders.NavigationFolder _navigation;
            MyCRMRepositoryFolders.OtherFolder _other;

            /// <summary>
            /// Creates a new MyCRM  folder.
            /// </summary>
            public MyCRMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyCRM", "/form[@controlname='Form1']/?/?", parentFolder, 30000, null, false, "49c06412-954f-4f86-8daa-ddc85200f715", "")
            {
                _people = new MyCRMRepositoryFolders.PeopleFolder(this);
                _company = new MyCRMRepositoryFolders.CompanyFolder(this);
                _navigation = new MyCRMRepositoryFolders.NavigationFolder(this);
                _other = new MyCRMRepositoryFolders.OtherFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("49c06412-954f-4f86-8daa-ddc85200f715")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("49c06412-954f-4f86-8daa-ddc85200f715")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The People folder.
            /// </summary>
            [RepositoryFolder("e94d6010-509d-4b53-8f15-61503a6a1411")]
            public virtual MyCRMRepositoryFolders.PeopleFolder People
            {
                get { return _people; }
            }

            /// <summary>
            /// The Company folder.
            /// </summary>
            [RepositoryFolder("6741e82e-ec3b-4d2f-8c4c-23dc101f2b01")]
            public virtual MyCRMRepositoryFolders.CompanyFolder Company
            {
                get { return _company; }
            }

            /// <summary>
            /// The Navigation folder.
            /// </summary>
            [RepositoryFolder("3c3167bb-0bd8-4bbe-ab1d-1513efefc36e")]
            public virtual MyCRMRepositoryFolders.NavigationFolder Navigation
            {
                get { return _navigation; }
            }

            /// <summary>
            /// The Other folder.
            /// </summary>
            [RepositoryFolder("37163c63-0c82-43a0-834c-9b5907690b82")]
            public virtual MyCRMRepositoryFolders.OtherFolder Other
            {
                get { return _other; }
            }
        }

        /// <summary>
        /// The PeopleFolder folder.
        /// </summary>
        [RepositoryFolder("e94d6010-509d-4b53-8f15-61503a6a1411")]
        public partial class PeopleFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstInfo;
            RepoItemInfo _lastInfo;
            RepoItemInfo _maleInfo;
            RepoItemInfo _femaleInfo;
            RepoItemInfo _addressline1Info;
            RepoItemInfo _addressline2Info;
            RepoItemInfo _cityInfo;
            RepoItemInfo _stateInfo;
            RepoItemInfo _zipInfo;
            RepoItemInfo _homeInfo;
            RepoItemInfo _workInfo;
            RepoItemInfo _mobileInfo;
            RepoItemInfo _personalmailInfo;
            RepoItemInfo _workmailInfo;
            RepoItemInfo _activeInfo;
            RepoItemInfo _commentsInfo;

            /// <summary>
            /// Creates a new People  folder.
            /// </summary>
            public PeopleFolder(RepoGenBaseFolder parentFolder) :
                    base("People", "", parentFolder, 0, null, false, "e94d6010-509d-4b53-8f15-61503a6a1411", "")
            {
                _firstInfo = new RepoItemInfo(this, "First", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox5']/?/?/text[@accessiblename='First:']", "", 30000, null, "38ff9c73-1bdf-468e-8567-eebdc3569b75");
                _lastInfo = new RepoItemInfo(this, "Last", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox5']/?/?/text[@accessiblename='Last:']", "", 30000, null, "1ff75e9c-8f84-4076-9191-c4bf9dc43cdb");
                _maleInfo = new RepoItemInfo(this, "Male", "tabpage[@controlname='tabPagePeople']/?/?/radiobutton[@controlname='radioButtonMale']", "", 30000, null, "e1801a9f-06ff-4048-a697-8099022b84f8");
                _femaleInfo = new RepoItemInfo(this, "Female", "tabpage[@controlname='tabPagePeople']/?/?/radiobutton[@controlname='radioButtonFemale']", "element", 30000, null, "875b9d47-71c9-4223-b268-7962bc5ee414");
                _addressline1Info = new RepoItemInfo(this, "Addressline1", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox1']/?/?/text[@accessiblename='Add Line 1:']", "element", 30000, null, "cdb4eb91-b0ee-4ca9-b162-29e8be384b9c");
                _addressline2Info = new RepoItemInfo(this, "Addressline2", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox1']/?/?/text[@accessiblename='Add Line 2:']", "element", 30000, null, "9ed4d4de-23e7-459f-b7e9-95e858087ab0");
                _cityInfo = new RepoItemInfo(this, "City", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox1']/?/?/text[@accessiblename='City:']", "element", 30000, null, "580cf3d3-59f7-4c3e-a161-f70ec03171b3");
                _stateInfo = new RepoItemInfo(this, "State", "tabpage[@controlname='tabPagePeople']/?/?/combobox[@controlname='comboBoxPeopleAddressState']", "element", 30000, null, "dda4586d-d628-4561-84d2-f0a3b845f13d");
                _zipInfo = new RepoItemInfo(this, "Zip", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox1']/?/?/text[@accessiblename='Zip:']", "element", 30000, null, "c9c0e1ea-89e5-4064-8a77-08ae5fade462");
                _homeInfo = new RepoItemInfo(this, "Home", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox2']/?/?/text[@accessiblename='Home:']", "element", 30000, null, "4fbaed2d-4c54-4b73-8030-6fe9e4a3ce8f");
                _workInfo = new RepoItemInfo(this, "Work", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox2']/?/?/text[@accessiblename='Work:']", "element", 30000, null, "fa3af862-a7cf-4af6-9f1a-c4ab39cfb8ec");
                _mobileInfo = new RepoItemInfo(this, "Mobile", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox2']/?/?/text[@accessiblename='Mobile:']", "element", 30000, null, "b3421d84-682e-4fad-b99f-1e9963912f88");
                _personalmailInfo = new RepoItemInfo(this, "Personalmail", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox4']/?/?/text[@accessiblename='Personal:']", "element", 30000, null, "3fc55c3a-aa05-4fc9-93a4-02b1a53a1324");
                _workmailInfo = new RepoItemInfo(this, "Workmail", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox4']/?/?/text[@accessiblename='Work:']", "element", 30000, null, "9fc16568-08b1-487a-9cbd-9726e9d4a2e7");
                _activeInfo = new RepoItemInfo(this, "Active", "tabpage[@controlname='tabPagePeople']/?/?/checkbox[@controlname='checkBox1']", "element", 30000, null, "11efd133-881c-477d-b063-d645a2d2e2a2");
                _commentsInfo = new RepoItemInfo(this, "Comments", "tabpage[@controlname='tabPagePeople']/container[@controlname='groupBox3']/?/?/text[@accessiblerole='Text']", "element", 30000, null, "ed6ea948-49ca-483c-abda-e08c8ca260b0");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e94d6010-509d-4b53-8f15-61503a6a1411")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The First item.
            /// </summary>
            [RepositoryItem("38ff9c73-1bdf-468e-8567-eebdc3569b75")]
            public virtual Ranorex.Text First
            {
                get
                {
                    return _firstInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The First item info.
            /// </summary>
            [RepositoryItemInfo("38ff9c73-1bdf-468e-8567-eebdc3569b75")]
            public virtual RepoItemInfo FirstInfo
            {
                get
                {
                    return _firstInfo;
                }
            }

            /// <summary>
            /// The Last item.
            /// </summary>
            [RepositoryItem("1ff75e9c-8f84-4076-9191-c4bf9dc43cdb")]
            public virtual Ranorex.Text Last
            {
                get
                {
                    return _lastInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Last item info.
            /// </summary>
            [RepositoryItemInfo("1ff75e9c-8f84-4076-9191-c4bf9dc43cdb")]
            public virtual RepoItemInfo LastInfo
            {
                get
                {
                    return _lastInfo;
                }
            }

            /// <summary>
            /// The Male item.
            /// </summary>
            [RepositoryItem("e1801a9f-06ff-4048-a697-8099022b84f8")]
            public virtual Ranorex.RadioButton Male
            {
                get
                {
                    return _maleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Male item info.
            /// </summary>
            [RepositoryItemInfo("e1801a9f-06ff-4048-a697-8099022b84f8")]
            public virtual RepoItemInfo MaleInfo
            {
                get
                {
                    return _maleInfo;
                }
            }

            /// <summary>
            /// The Female item.
            /// </summary>
            [RepositoryItem("875b9d47-71c9-4223-b268-7962bc5ee414")]
            public virtual Ranorex.RadioButton Female
            {
                get
                {
                    return _femaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Female item info.
            /// </summary>
            [RepositoryItemInfo("875b9d47-71c9-4223-b268-7962bc5ee414")]
            public virtual RepoItemInfo FemaleInfo
            {
                get
                {
                    return _femaleInfo;
                }
            }

            /// <summary>
            /// The Addressline1 item.
            /// </summary>
            [RepositoryItem("cdb4eb91-b0ee-4ca9-b162-29e8be384b9c")]
            public virtual Ranorex.Text Addressline1
            {
                get
                {
                    return _addressline1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Addressline1 item info.
            /// </summary>
            [RepositoryItemInfo("cdb4eb91-b0ee-4ca9-b162-29e8be384b9c")]
            public virtual RepoItemInfo Addressline1Info
            {
                get
                {
                    return _addressline1Info;
                }
            }

            /// <summary>
            /// The Addressline2 item.
            /// </summary>
            [RepositoryItem("9ed4d4de-23e7-459f-b7e9-95e858087ab0")]
            public virtual Ranorex.Text Addressline2
            {
                get
                {
                    return _addressline2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Addressline2 item info.
            /// </summary>
            [RepositoryItemInfo("9ed4d4de-23e7-459f-b7e9-95e858087ab0")]
            public virtual RepoItemInfo Addressline2Info
            {
                get
                {
                    return _addressline2Info;
                }
            }

            /// <summary>
            /// The City item.
            /// </summary>
            [RepositoryItem("580cf3d3-59f7-4c3e-a161-f70ec03171b3")]
            public virtual Ranorex.Text City
            {
                get
                {
                    return _cityInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The City item info.
            /// </summary>
            [RepositoryItemInfo("580cf3d3-59f7-4c3e-a161-f70ec03171b3")]
            public virtual RepoItemInfo CityInfo
            {
                get
                {
                    return _cityInfo;
                }
            }

            /// <summary>
            /// The State item.
            /// </summary>
            [RepositoryItem("dda4586d-d628-4561-84d2-f0a3b845f13d")]
            public virtual Ranorex.ComboBox State
            {
                get
                {
                    return _stateInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The State item info.
            /// </summary>
            [RepositoryItemInfo("dda4586d-d628-4561-84d2-f0a3b845f13d")]
            public virtual RepoItemInfo StateInfo
            {
                get
                {
                    return _stateInfo;
                }
            }

            /// <summary>
            /// The Zip item.
            /// </summary>
            [RepositoryItem("c9c0e1ea-89e5-4064-8a77-08ae5fade462")]
            public virtual Ranorex.Text Zip
            {
                get
                {
                    return _zipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Zip item info.
            /// </summary>
            [RepositoryItemInfo("c9c0e1ea-89e5-4064-8a77-08ae5fade462")]
            public virtual RepoItemInfo ZipInfo
            {
                get
                {
                    return _zipInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("4fbaed2d-4c54-4b73-8030-6fe9e4a3ce8f")]
            public virtual Ranorex.Text Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("4fbaed2d-4c54-4b73-8030-6fe9e4a3ce8f")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The Work item.
            /// </summary>
            [RepositoryItem("fa3af862-a7cf-4af6-9f1a-c4ab39cfb8ec")]
            public virtual Ranorex.Text Work
            {
                get
                {
                    return _workInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Work item info.
            /// </summary>
            [RepositoryItemInfo("fa3af862-a7cf-4af6-9f1a-c4ab39cfb8ec")]
            public virtual RepoItemInfo WorkInfo
            {
                get
                {
                    return _workInfo;
                }
            }

            /// <summary>
            /// The Mobile item.
            /// </summary>
            [RepositoryItem("b3421d84-682e-4fad-b99f-1e9963912f88")]
            public virtual Ranorex.Text Mobile
            {
                get
                {
                    return _mobileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Mobile item info.
            /// </summary>
            [RepositoryItemInfo("b3421d84-682e-4fad-b99f-1e9963912f88")]
            public virtual RepoItemInfo MobileInfo
            {
                get
                {
                    return _mobileInfo;
                }
            }

            /// <summary>
            /// The Personalmail item.
            /// </summary>
            [RepositoryItem("3fc55c3a-aa05-4fc9-93a4-02b1a53a1324")]
            public virtual Ranorex.Text Personalmail
            {
                get
                {
                    return _personalmailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Personalmail item info.
            /// </summary>
            [RepositoryItemInfo("3fc55c3a-aa05-4fc9-93a4-02b1a53a1324")]
            public virtual RepoItemInfo PersonalmailInfo
            {
                get
                {
                    return _personalmailInfo;
                }
            }

            /// <summary>
            /// The Workmail item.
            /// </summary>
            [RepositoryItem("9fc16568-08b1-487a-9cbd-9726e9d4a2e7")]
            public virtual Ranorex.Text Workmail
            {
                get
                {
                    return _workmailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Workmail item info.
            /// </summary>
            [RepositoryItemInfo("9fc16568-08b1-487a-9cbd-9726e9d4a2e7")]
            public virtual RepoItemInfo WorkmailInfo
            {
                get
                {
                    return _workmailInfo;
                }
            }

            /// <summary>
            /// The Active item.
            /// </summary>
            [RepositoryItem("11efd133-881c-477d-b063-d645a2d2e2a2")]
            public virtual Ranorex.CheckBox Active
            {
                get
                {
                    return _activeInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The Active item info.
            /// </summary>
            [RepositoryItemInfo("11efd133-881c-477d-b063-d645a2d2e2a2")]
            public virtual RepoItemInfo ActiveInfo
            {
                get
                {
                    return _activeInfo;
                }
            }

            /// <summary>
            /// The Comments item.
            /// </summary>
            [RepositoryItem("ed6ea948-49ca-483c-abda-e08c8ca260b0")]
            public virtual Ranorex.Text Comments
            {
                get
                {
                    return _commentsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Comments item info.
            /// </summary>
            [RepositoryItemInfo("ed6ea948-49ca-483c-abda-e08c8ca260b0")]
            public virtual RepoItemInfo CommentsInfo
            {
                get
                {
                    return _commentsInfo;
                }
            }
        }

        /// <summary>
        /// The CompanyFolder folder.
        /// </summary>
        [RepositoryFolder("6741e82e-ec3b-4d2f-8c4c-23dc101f2b01")]
        public partial class CompanyFolder : RepoGenBaseFolder
        {
            RepoItemInfo _labeladdline1Info;
            RepoItemInfo _labeladdline2Info;
            RepoItemInfo _labelcityInfo;
            RepoItemInfo _labelstateInfo;
            RepoItemInfo _labelzipInfo;
            RepoItemInfo _labemainInfo;
            RepoItemInfo _labelotherInfo;
            RepoItemInfo _dropdownstateInfo;
            RepoItemInfo _commentboxInfo;
            RepoItemInfo _txtaddressline1Info;
            RepoItemInfo _txtaddressline2Info;
            RepoItemInfo _txtcityInfo;
            RepoItemInfo _txtzipInfo;
            RepoItemInfo _txtmainInfo;
            RepoItemInfo _txtotherInfo;

            /// <summary>
            /// Creates a new Company  folder.
            /// </summary>
            public CompanyFolder(RepoGenBaseFolder parentFolder) :
                    base("Company", "", parentFolder, 0, null, false, "6741e82e-ec3b-4d2f-8c4c-23dc101f2b01", "")
            {
                _labeladdline1Info = new RepoItemInfo(this, "LabelAddLine1", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='label22']", "element", 30000, null, "7b75f60f-32b6-4f20-9418-16e6c61b62d6");
                _labeladdline2Info = new RepoItemInfo(this, "LabelAddLine2", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='label21']", "element", 30000, null, "7e363e15-abc4-4287-a46b-bcee1a06d4f1");
                _labelcityInfo = new RepoItemInfo(this, "LabelCity", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='label20']", "element", 30000, null, "779072db-e2e8-470f-adc0-5380f608e5a4");
                _labelstateInfo = new RepoItemInfo(this, "LabelState", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='label19']", "element", 30000, null, "df73478f-20e8-4720-95cb-13764a4229e4");
                _labelzipInfo = new RepoItemInfo(this, "LabelZip", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='label18']", "element", 30000, null, "f5c6e247-fa1d-43ee-80d1-5712f26e316f");
                _labemainInfo = new RepoItemInfo(this, "LabeMain", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='label17']", "element", 30000, null, "8337b98d-a2b2-4def-b286-35bcd8c48525");
                _labelotherInfo = new RepoItemInfo(this, "LabelOther", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='label16']", "element", 30000, null, "5d4a6c93-4aae-4ed3-8730-9121950548a5");
                _dropdownstateInfo = new RepoItemInfo(this, "DropDownState", "tabpage[@controlname='tabPageCompanies']/?/?/combobox[@controlname='comboBoxCompaniesAddressState']", "element", 30000, null, "e65fc614-8bd2-4d04-9252-de0eb6329387");
                _commentboxInfo = new RepoItemInfo(this, "CommentBox", "tabpage[@controlname='tabPageCompanies']/container[@controlname='groupBox7']/?/?/text[@accessiblerole='Text']", "element", 30000, null, "f6838123-bdd2-4b00-9eb6-cb045d61d0e3");
                _txtaddressline1Info = new RepoItemInfo(this, "TxtAddressLine1", "tabpage[@controlname='tabPageCompanies']/container[@controlname='groupBox9']/?/?/text[@accessiblename='Add Line 1:']", "element", 30000, null, "b60ecbbf-17c2-4de7-933e-459db99e9516");
                _txtaddressline2Info = new RepoItemInfo(this, "TxtAddressLine2", "tabpage[@controlname='tabPageCompanies']/container[@controlname='groupBox9']/?/?/text[@accessiblename='Add Line 2:']", "element", 30000, null, "49a26305-d674-4995-8ccd-341ed6f8f41d");
                _txtcityInfo = new RepoItemInfo(this, "TxtCity", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='textBoxCompaniesAddressCity']", "element", 30000, null, "d87c6fc7-70eb-4d03-b9fa-f153e34ced75");
                _txtzipInfo = new RepoItemInfo(this, "TxtZip", "tabpage[@controlname='tabPageCompanies']/?/?/text[@controlname='textBoxCompaniesAddressZip']", "element", 30000, null, "4ab49ece-250a-4c49-9613-d35e539e5a1e");
                _txtmainInfo = new RepoItemInfo(this, "TxtMain", "tabpage[@controlname='tabPageCompanies']/container[@controlname='groupBox8']/?/?/text[@accessiblename='Main:']", "element", 30000, null, "c0fe8e77-830f-4264-baa5-eab05b48b368");
                _txtotherInfo = new RepoItemInfo(this, "TxtOther", "tabpage[@controlname='tabPageCompanies']/container[@controlname='groupBox8']/?/?/text[@accessiblename='Other:']", "element", 30000, null, "202b68c9-d382-4b20-897b-bf688bb3e1b3");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6741e82e-ec3b-4d2f-8c4c-23dc101f2b01")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LabelAddLine1 item.
            /// </summary>
            [RepositoryItem("7b75f60f-32b6-4f20-9418-16e6c61b62d6")]
            public virtual Ranorex.Text LabelAddLine1
            {
                get
                {
                    return _labeladdline1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelAddLine1 item info.
            /// </summary>
            [RepositoryItemInfo("7b75f60f-32b6-4f20-9418-16e6c61b62d6")]
            public virtual RepoItemInfo LabelAddLine1Info
            {
                get
                {
                    return _labeladdline1Info;
                }
            }

            /// <summary>
            /// The LabelAddLine2 item.
            /// </summary>
            [RepositoryItem("7e363e15-abc4-4287-a46b-bcee1a06d4f1")]
            public virtual Ranorex.Text LabelAddLine2
            {
                get
                {
                    return _labeladdline2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelAddLine2 item info.
            /// </summary>
            [RepositoryItemInfo("7e363e15-abc4-4287-a46b-bcee1a06d4f1")]
            public virtual RepoItemInfo LabelAddLine2Info
            {
                get
                {
                    return _labeladdline2Info;
                }
            }

            /// <summary>
            /// The LabelCity item.
            /// </summary>
            [RepositoryItem("779072db-e2e8-470f-adc0-5380f608e5a4")]
            public virtual Ranorex.Text LabelCity
            {
                get
                {
                    return _labelcityInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelCity item info.
            /// </summary>
            [RepositoryItemInfo("779072db-e2e8-470f-adc0-5380f608e5a4")]
            public virtual RepoItemInfo LabelCityInfo
            {
                get
                {
                    return _labelcityInfo;
                }
            }

            /// <summary>
            /// The LabelState item.
            /// </summary>
            [RepositoryItem("df73478f-20e8-4720-95cb-13764a4229e4")]
            public virtual Ranorex.Text LabelState
            {
                get
                {
                    return _labelstateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelState item info.
            /// </summary>
            [RepositoryItemInfo("df73478f-20e8-4720-95cb-13764a4229e4")]
            public virtual RepoItemInfo LabelStateInfo
            {
                get
                {
                    return _labelstateInfo;
                }
            }

            /// <summary>
            /// The LabelZip item.
            /// </summary>
            [RepositoryItem("f5c6e247-fa1d-43ee-80d1-5712f26e316f")]
            public virtual Ranorex.Text LabelZip
            {
                get
                {
                    return _labelzipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelZip item info.
            /// </summary>
            [RepositoryItemInfo("f5c6e247-fa1d-43ee-80d1-5712f26e316f")]
            public virtual RepoItemInfo LabelZipInfo
            {
                get
                {
                    return _labelzipInfo;
                }
            }

            /// <summary>
            /// The LabeMain item.
            /// </summary>
            [RepositoryItem("8337b98d-a2b2-4def-b286-35bcd8c48525")]
            public virtual Ranorex.Text LabeMain
            {
                get
                {
                    return _labemainInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabeMain item info.
            /// </summary>
            [RepositoryItemInfo("8337b98d-a2b2-4def-b286-35bcd8c48525")]
            public virtual RepoItemInfo LabeMainInfo
            {
                get
                {
                    return _labemainInfo;
                }
            }

            /// <summary>
            /// The LabelOther item.
            /// </summary>
            [RepositoryItem("5d4a6c93-4aae-4ed3-8730-9121950548a5")]
            public virtual Ranorex.Text LabelOther
            {
                get
                {
                    return _labelotherInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelOther item info.
            /// </summary>
            [RepositoryItemInfo("5d4a6c93-4aae-4ed3-8730-9121950548a5")]
            public virtual RepoItemInfo LabelOtherInfo
            {
                get
                {
                    return _labelotherInfo;
                }
            }

            /// <summary>
            /// The DropDownState item.
            /// </summary>
            [RepositoryItem("e65fc614-8bd2-4d04-9252-de0eb6329387")]
            public virtual Ranorex.ComboBox DropDownState
            {
                get
                {
                    return _dropdownstateInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The DropDownState item info.
            /// </summary>
            [RepositoryItemInfo("e65fc614-8bd2-4d04-9252-de0eb6329387")]
            public virtual RepoItemInfo DropDownStateInfo
            {
                get
                {
                    return _dropdownstateInfo;
                }
            }

            /// <summary>
            /// The CommentBox item.
            /// </summary>
            [RepositoryItem("f6838123-bdd2-4b00-9eb6-cb045d61d0e3")]
            public virtual Ranorex.Text CommentBox
            {
                get
                {
                    return _commentboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CommentBox item info.
            /// </summary>
            [RepositoryItemInfo("f6838123-bdd2-4b00-9eb6-cb045d61d0e3")]
            public virtual RepoItemInfo CommentBoxInfo
            {
                get
                {
                    return _commentboxInfo;
                }
            }

            /// <summary>
            /// The TxtAddressLine1 item.
            /// </summary>
            [RepositoryItem("b60ecbbf-17c2-4de7-933e-459db99e9516")]
            public virtual Ranorex.Text TxtAddressLine1
            {
                get
                {
                    return _txtaddressline1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtAddressLine1 item info.
            /// </summary>
            [RepositoryItemInfo("b60ecbbf-17c2-4de7-933e-459db99e9516")]
            public virtual RepoItemInfo TxtAddressLine1Info
            {
                get
                {
                    return _txtaddressline1Info;
                }
            }

            /// <summary>
            /// The TxtAddressLine2 item.
            /// </summary>
            [RepositoryItem("49a26305-d674-4995-8ccd-341ed6f8f41d")]
            public virtual Ranorex.Text TxtAddressLine2
            {
                get
                {
                    return _txtaddressline2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtAddressLine2 item info.
            /// </summary>
            [RepositoryItemInfo("49a26305-d674-4995-8ccd-341ed6f8f41d")]
            public virtual RepoItemInfo TxtAddressLine2Info
            {
                get
                {
                    return _txtaddressline2Info;
                }
            }

            /// <summary>
            /// The TxtCity item.
            /// </summary>
            [RepositoryItem("d87c6fc7-70eb-4d03-b9fa-f153e34ced75")]
            public virtual Ranorex.Text TxtCity
            {
                get
                {
                    return _txtcityInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtCity item info.
            /// </summary>
            [RepositoryItemInfo("d87c6fc7-70eb-4d03-b9fa-f153e34ced75")]
            public virtual RepoItemInfo TxtCityInfo
            {
                get
                {
                    return _txtcityInfo;
                }
            }

            /// <summary>
            /// The TxtZip item.
            /// </summary>
            [RepositoryItem("4ab49ece-250a-4c49-9613-d35e539e5a1e")]
            public virtual Ranorex.Text TxtZip
            {
                get
                {
                    return _txtzipInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtZip item info.
            /// </summary>
            [RepositoryItemInfo("4ab49ece-250a-4c49-9613-d35e539e5a1e")]
            public virtual RepoItemInfo TxtZipInfo
            {
                get
                {
                    return _txtzipInfo;
                }
            }

            /// <summary>
            /// The TxtMain item.
            /// </summary>
            [RepositoryItem("c0fe8e77-830f-4264-baa5-eab05b48b368")]
            public virtual Ranorex.Text TxtMain
            {
                get
                {
                    return _txtmainInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtMain item info.
            /// </summary>
            [RepositoryItemInfo("c0fe8e77-830f-4264-baa5-eab05b48b368")]
            public virtual RepoItemInfo TxtMainInfo
            {
                get
                {
                    return _txtmainInfo;
                }
            }

            /// <summary>
            /// The TxtOther item.
            /// </summary>
            [RepositoryItem("202b68c9-d382-4b20-897b-bf688bb3e1b3")]
            public virtual Ranorex.Text TxtOther
            {
                get
                {
                    return _txtotherInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtOther item info.
            /// </summary>
            [RepositoryItemInfo("202b68c9-d382-4b20-897b-bf688bb3e1b3")]
            public virtual RepoItemInfo TxtOtherInfo
            {
                get
                {
                    return _txtotherInfo;
                }
            }
        }

        /// <summary>
        /// The NavigationFolder folder.
        /// </summary>
        [RepositoryFolder("3c3167bb-0bd8-4bbe-ab1d-1513efefc36e")]
        public partial class NavigationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _companyInfo;
            RepoItemInfo _otherInfo;

            /// <summary>
            /// Creates a new Navigation  folder.
            /// </summary>
            public NavigationFolder(RepoGenBaseFolder parentFolder) :
                    base("Navigation", "", parentFolder, 0, null, false, "3c3167bb-0bd8-4bbe-ab1d-1513efefc36e", "")
            {
                _companyInfo = new RepoItemInfo(this, "Company", "tabpage[@accessiblename='Company ']", "element", 30000, null, "c3394663-c50f-4003-8abf-2e349bdfca82");
                _otherInfo = new RepoItemInfo(this, "Other", "tabpage[@accessiblename='Other']", "element", 30000, null, "cd615060-2b63-404c-a29c-dbc2ed51514c");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3c3167bb-0bd8-4bbe-ab1d-1513efefc36e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Company item.
            /// </summary>
            [RepositoryItem("c3394663-c50f-4003-8abf-2e349bdfca82")]
            public virtual Ranorex.TabPage Company
            {
                get
                {
                    return _companyInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Company item info.
            /// </summary>
            [RepositoryItemInfo("c3394663-c50f-4003-8abf-2e349bdfca82")]
            public virtual RepoItemInfo CompanyInfo
            {
                get
                {
                    return _companyInfo;
                }
            }

            /// <summary>
            /// The Other item.
            /// </summary>
            [RepositoryItem("cd615060-2b63-404c-a29c-dbc2ed51514c")]
            public virtual Ranorex.TabPage Other
            {
                get
                {
                    return _otherInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Other item info.
            /// </summary>
            [RepositoryItemInfo("cd615060-2b63-404c-a29c-dbc2ed51514c")]
            public virtual RepoItemInfo OtherInfo
            {
                get
                {
                    return _otherInfo;
                }
            }
        }

        /// <summary>
        /// The OtherFolder folder.
        /// </summary>
        [RepositoryFolder("37163c63-0c82-43a0-834c-9b5907690b82")]
        public partial class OtherFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lnkgeneric1Info;
            RepoItemInfo _linkgeneric2Info;
            RepoItemInfo _linkgeneric3Info;
            RepoItemInfo _linkgeneric4Info;
            RepoItemInfo _linkgeneric5Info;
            RepoItemInfo _linkgeneric6Info;
            RepoItemInfo _linkgeneric7Info;
            RepoItemInfo _linkgeneric8Info;
            RepoItemInfo _linkgeneric9Info;
            RepoItemInfo _linkgeneric10Info;
            RepoItemInfo _browseInfo;
            RepoItemInfo _saveInfo;
            RepoItemInfo _txtgeneric1Info;
            RepoItemInfo _txtgeneric2Info;
            RepoItemInfo _txtgeneric3Info;
            RepoItemInfo _txtgeneric4Info;
            RepoItemInfo _txtgeneric5Info;
            RepoItemInfo _txtgeneric6Info;
            RepoItemInfo _txtgeneric7Info;
            RepoItemInfo _txtgeneric8Info;
            RepoItemInfo _txtgeneric9Info;
            RepoItemInfo _txtgeneric10Info;

            /// <summary>
            /// Creates a new Other  folder.
            /// </summary>
            public OtherFolder(RepoGenBaseFolder parentFolder) :
                    base("Other", "", parentFolder, 0, null, false, "37163c63-0c82-43a0-834c-9b5907690b82", "")
            {
                _lnkgeneric1Info = new RepoItemInfo(this, "LnkGeneric1", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric1']/?/?/link[@accessiblename='Generic 1:']", "element", 30000, null, "aa24db8c-eb2d-4460-81b4-f98eac0a106e");
                _linkgeneric2Info = new RepoItemInfo(this, "LinkGeneric2", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric2']/?/?/link[@accessiblename='Generic 2:']", "element", 30000, null, "a96d5c52-236f-4ac4-9ac7-50eed7ac9436");
                _linkgeneric3Info = new RepoItemInfo(this, "LinkGeneric3", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric3']/?/?/link[@accessiblename='Generic 3:']", "element", 30000, null, "efae864f-c705-49f0-b31c-f60dbe078107");
                _linkgeneric4Info = new RepoItemInfo(this, "LinkGeneric4", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric4']/?/?/link[@accessiblename='Generic 4:']", "element", 30000, null, "c2a5c43a-95fb-4fa5-9e8c-6b65be7680a3");
                _linkgeneric5Info = new RepoItemInfo(this, "LinkGeneric5", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric5']/?/?/link[@accessiblename='Generic 5:']", "element", 30000, null, "a3eb14c5-c88f-4e7c-8ebb-a142c2be3978");
                _linkgeneric6Info = new RepoItemInfo(this, "LinkGeneric6", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric6']/?/?/link[@accessiblename='Generic 6:']", "element", 30000, null, "287fbece-84df-4352-ba11-f5b1bbb55477");
                _linkgeneric7Info = new RepoItemInfo(this, "LinkGeneric7", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric7']/?/?/link[@accessiblename='Generic 7:']", "element", 30000, null, "1b13d570-287a-4c47-91e7-33ea31468d82");
                _linkgeneric8Info = new RepoItemInfo(this, "LinkGeneric8", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric8']/?/?/link[@accessiblename='Generic 8:']", "element", 30000, null, "19635c85-dca9-4585-846a-62265a510d52");
                _linkgeneric9Info = new RepoItemInfo(this, "LinkGeneric9", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric9']/?/?/link[@accessiblename='Generic 9:']", "element", 30000, null, "75007f5b-14f3-46c9-b2a6-4ef8ad12281b");
                _linkgeneric10Info = new RepoItemInfo(this, "LinkGeneric10", "tabpage[@controlname='tabPage4']/?/?/link[@controlname='linkLabelGeneric10']/?/?/link[@accessiblename='Generic 10:']", "element", 30000, null, "6f932c7f-09b8-4add-bd0d-6d9849505c3e");
                _browseInfo = new RepoItemInfo(this, "Browse", "tabpage[@controlname='tabPage4']/?/?/button[@controlname='button2']", "element", 30000, null, "1ccddaa3-8873-4801-a801-dbfa076f5ac6");
                _saveInfo = new RepoItemInfo(this, "Save", "tabpage[@controlname='tabPage4']/?/?/button[@controlname='button1']", "element", 30000, null, "b15c5891-c7a6-44bd-81b6-7e220a130b04");
                _txtgeneric1Info = new RepoItemInfo(this, "TxtGeneric1", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox8']/text[@accessiblename='Other:']", "element", 30000, null, "dbfd88ee-63fd-4a97-bd45-f282b3e26af8");
                _txtgeneric2Info = new RepoItemInfo(this, "TxtGeneric2", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox7']/text[@accessiblerole='Text']", "element", 30000, null, "8b2d04ce-4448-4265-9225-14b2943d9bb9");
                _txtgeneric3Info = new RepoItemInfo(this, "TxtGeneric3", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox3']/text[@accessiblerole='Text']", "element", 30000, null, "077dddd6-ef1e-464f-8135-d414ddee41d4");
                _txtgeneric4Info = new RepoItemInfo(this, "TxtGeneric4", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox2']/text[@accessiblerole='Text']", "element", 30000, null, "63a13efb-fd4c-483a-9924-7bd2cdaaf00b");
                _txtgeneric5Info = new RepoItemInfo(this, "TxtGeneric5", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox1']/text[@accessiblerole='Text']", "element", 30000, null, "2fd1ea0c-2721-41f4-b5fa-b11145a32f32");
                _txtgeneric6Info = new RepoItemInfo(this, "TxtGeneric6", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox13']/text[@accessiblerole='Text']", "element", 30000, null, "57995e17-61a5-4379-9194-a46cbc0c11c4");
                _txtgeneric7Info = new RepoItemInfo(this, "TxtGeneric7", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox12']/text[@accessiblerole='Text']", "element", 30000, null, "2fea7856-340c-4eca-96a7-afa95c0a3ffe");
                _txtgeneric8Info = new RepoItemInfo(this, "TxtGeneric8", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox11']/text[@accessiblerole='Text']", "element", 30000, null, "5db4037a-0983-4032-b8b4-9788d5d330b7");
                _txtgeneric9Info = new RepoItemInfo(this, "TxtGeneric9", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox10']/text[@accessiblerole='Text']", "element", 30000, null, "747327fd-4b6c-483e-a202-fb67e90426d8");
                _txtgeneric10Info = new RepoItemInfo(this, "TxtGeneric10", "tabpage[@controlname='tabPage4']/?/?/text[@controlname='textBox9']/text[@accessiblerole='Text']", "element", 30000, null, "60333416-8525-42cf-aab8-1111878cf713");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("37163c63-0c82-43a0-834c-9b5907690b82")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LnkGeneric1 item.
            /// </summary>
            [RepositoryItem("aa24db8c-eb2d-4460-81b4-f98eac0a106e")]
            public virtual Ranorex.Link LnkGeneric1
            {
                get
                {
                    return _lnkgeneric1Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LnkGeneric1 item info.
            /// </summary>
            [RepositoryItemInfo("aa24db8c-eb2d-4460-81b4-f98eac0a106e")]
            public virtual RepoItemInfo LnkGeneric1Info
            {
                get
                {
                    return _lnkgeneric1Info;
                }
            }

            /// <summary>
            /// The LinkGeneric2 item.
            /// </summary>
            [RepositoryItem("a96d5c52-236f-4ac4-9ac7-50eed7ac9436")]
            public virtual Ranorex.Link LinkGeneric2
            {
                get
                {
                    return _linkgeneric2Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric2 item info.
            /// </summary>
            [RepositoryItemInfo("a96d5c52-236f-4ac4-9ac7-50eed7ac9436")]
            public virtual RepoItemInfo LinkGeneric2Info
            {
                get
                {
                    return _linkgeneric2Info;
                }
            }

            /// <summary>
            /// The LinkGeneric3 item.
            /// </summary>
            [RepositoryItem("efae864f-c705-49f0-b31c-f60dbe078107")]
            public virtual Ranorex.Link LinkGeneric3
            {
                get
                {
                    return _linkgeneric3Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric3 item info.
            /// </summary>
            [RepositoryItemInfo("efae864f-c705-49f0-b31c-f60dbe078107")]
            public virtual RepoItemInfo LinkGeneric3Info
            {
                get
                {
                    return _linkgeneric3Info;
                }
            }

            /// <summary>
            /// The LinkGeneric4 item.
            /// </summary>
            [RepositoryItem("c2a5c43a-95fb-4fa5-9e8c-6b65be7680a3")]
            public virtual Ranorex.Link LinkGeneric4
            {
                get
                {
                    return _linkgeneric4Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric4 item info.
            /// </summary>
            [RepositoryItemInfo("c2a5c43a-95fb-4fa5-9e8c-6b65be7680a3")]
            public virtual RepoItemInfo LinkGeneric4Info
            {
                get
                {
                    return _linkgeneric4Info;
                }
            }

            /// <summary>
            /// The LinkGeneric5 item.
            /// </summary>
            [RepositoryItem("a3eb14c5-c88f-4e7c-8ebb-a142c2be3978")]
            public virtual Ranorex.Link LinkGeneric5
            {
                get
                {
                    return _linkgeneric5Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric5 item info.
            /// </summary>
            [RepositoryItemInfo("a3eb14c5-c88f-4e7c-8ebb-a142c2be3978")]
            public virtual RepoItemInfo LinkGeneric5Info
            {
                get
                {
                    return _linkgeneric5Info;
                }
            }

            /// <summary>
            /// The LinkGeneric6 item.
            /// </summary>
            [RepositoryItem("287fbece-84df-4352-ba11-f5b1bbb55477")]
            public virtual Ranorex.Link LinkGeneric6
            {
                get
                {
                    return _linkgeneric6Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric6 item info.
            /// </summary>
            [RepositoryItemInfo("287fbece-84df-4352-ba11-f5b1bbb55477")]
            public virtual RepoItemInfo LinkGeneric6Info
            {
                get
                {
                    return _linkgeneric6Info;
                }
            }

            /// <summary>
            /// The LinkGeneric7 item.
            /// </summary>
            [RepositoryItem("1b13d570-287a-4c47-91e7-33ea31468d82")]
            public virtual Ranorex.Link LinkGeneric7
            {
                get
                {
                    return _linkgeneric7Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric7 item info.
            /// </summary>
            [RepositoryItemInfo("1b13d570-287a-4c47-91e7-33ea31468d82")]
            public virtual RepoItemInfo LinkGeneric7Info
            {
                get
                {
                    return _linkgeneric7Info;
                }
            }

            /// <summary>
            /// The LinkGeneric8 item.
            /// </summary>
            [RepositoryItem("19635c85-dca9-4585-846a-62265a510d52")]
            public virtual Ranorex.Link LinkGeneric8
            {
                get
                {
                    return _linkgeneric8Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric8 item info.
            /// </summary>
            [RepositoryItemInfo("19635c85-dca9-4585-846a-62265a510d52")]
            public virtual RepoItemInfo LinkGeneric8Info
            {
                get
                {
                    return _linkgeneric8Info;
                }
            }

            /// <summary>
            /// The LinkGeneric9 item.
            /// </summary>
            [RepositoryItem("75007f5b-14f3-46c9-b2a6-4ef8ad12281b")]
            public virtual Ranorex.Link LinkGeneric9
            {
                get
                {
                    return _linkgeneric9Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric9 item info.
            /// </summary>
            [RepositoryItemInfo("75007f5b-14f3-46c9-b2a6-4ef8ad12281b")]
            public virtual RepoItemInfo LinkGeneric9Info
            {
                get
                {
                    return _linkgeneric9Info;
                }
            }

            /// <summary>
            /// The LinkGeneric10 item.
            /// </summary>
            [RepositoryItem("6f932c7f-09b8-4add-bd0d-6d9849505c3e")]
            public virtual Ranorex.Link LinkGeneric10
            {
                get
                {
                    return _linkgeneric10Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkGeneric10 item info.
            /// </summary>
            [RepositoryItemInfo("6f932c7f-09b8-4add-bd0d-6d9849505c3e")]
            public virtual RepoItemInfo LinkGeneric10Info
            {
                get
                {
                    return _linkgeneric10Info;
                }
            }

            /// <summary>
            /// The Browse item.
            /// </summary>
            [RepositoryItem("1ccddaa3-8873-4801-a801-dbfa076f5ac6")]
            public virtual Ranorex.Button Browse
            {
                get
                {
                    return _browseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Browse item info.
            /// </summary>
            [RepositoryItemInfo("1ccddaa3-8873-4801-a801-dbfa076f5ac6")]
            public virtual RepoItemInfo BrowseInfo
            {
                get
                {
                    return _browseInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("b15c5891-c7a6-44bd-81b6-7e220a130b04")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("b15c5891-c7a6-44bd-81b6-7e220a130b04")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The TxtGeneric1 item.
            /// </summary>
            [RepositoryItem("dbfd88ee-63fd-4a97-bd45-f282b3e26af8")]
            public virtual Ranorex.Text TxtGeneric1
            {
                get
                {
                    return _txtgeneric1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric1 item info.
            /// </summary>
            [RepositoryItemInfo("dbfd88ee-63fd-4a97-bd45-f282b3e26af8")]
            public virtual RepoItemInfo TxtGeneric1Info
            {
                get
                {
                    return _txtgeneric1Info;
                }
            }

            /// <summary>
            /// The TxtGeneric2 item.
            /// </summary>
            [RepositoryItem("8b2d04ce-4448-4265-9225-14b2943d9bb9")]
            public virtual Ranorex.Text TxtGeneric2
            {
                get
                {
                    return _txtgeneric2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric2 item info.
            /// </summary>
            [RepositoryItemInfo("8b2d04ce-4448-4265-9225-14b2943d9bb9")]
            public virtual RepoItemInfo TxtGeneric2Info
            {
                get
                {
                    return _txtgeneric2Info;
                }
            }

            /// <summary>
            /// The TxtGeneric3 item.
            /// </summary>
            [RepositoryItem("077dddd6-ef1e-464f-8135-d414ddee41d4")]
            public virtual Ranorex.Text TxtGeneric3
            {
                get
                {
                    return _txtgeneric3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric3 item info.
            /// </summary>
            [RepositoryItemInfo("077dddd6-ef1e-464f-8135-d414ddee41d4")]
            public virtual RepoItemInfo TxtGeneric3Info
            {
                get
                {
                    return _txtgeneric3Info;
                }
            }

            /// <summary>
            /// The TxtGeneric4 item.
            /// </summary>
            [RepositoryItem("63a13efb-fd4c-483a-9924-7bd2cdaaf00b")]
            public virtual Ranorex.Text TxtGeneric4
            {
                get
                {
                    return _txtgeneric4Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric4 item info.
            /// </summary>
            [RepositoryItemInfo("63a13efb-fd4c-483a-9924-7bd2cdaaf00b")]
            public virtual RepoItemInfo TxtGeneric4Info
            {
                get
                {
                    return _txtgeneric4Info;
                }
            }

            /// <summary>
            /// The TxtGeneric5 item.
            /// </summary>
            [RepositoryItem("2fd1ea0c-2721-41f4-b5fa-b11145a32f32")]
            public virtual Ranorex.Text TxtGeneric5
            {
                get
                {
                    return _txtgeneric5Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric5 item info.
            /// </summary>
            [RepositoryItemInfo("2fd1ea0c-2721-41f4-b5fa-b11145a32f32")]
            public virtual RepoItemInfo TxtGeneric5Info
            {
                get
                {
                    return _txtgeneric5Info;
                }
            }

            /// <summary>
            /// The TxtGeneric6 item.
            /// </summary>
            [RepositoryItem("57995e17-61a5-4379-9194-a46cbc0c11c4")]
            public virtual Ranorex.Text TxtGeneric6
            {
                get
                {
                    return _txtgeneric6Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric6 item info.
            /// </summary>
            [RepositoryItemInfo("57995e17-61a5-4379-9194-a46cbc0c11c4")]
            public virtual RepoItemInfo TxtGeneric6Info
            {
                get
                {
                    return _txtgeneric6Info;
                }
            }

            /// <summary>
            /// The TxtGeneric7 item.
            /// </summary>
            [RepositoryItem("2fea7856-340c-4eca-96a7-afa95c0a3ffe")]
            public virtual Ranorex.Text TxtGeneric7
            {
                get
                {
                    return _txtgeneric7Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric7 item info.
            /// </summary>
            [RepositoryItemInfo("2fea7856-340c-4eca-96a7-afa95c0a3ffe")]
            public virtual RepoItemInfo TxtGeneric7Info
            {
                get
                {
                    return _txtgeneric7Info;
                }
            }

            /// <summary>
            /// The TxtGeneric8 item.
            /// </summary>
            [RepositoryItem("5db4037a-0983-4032-b8b4-9788d5d330b7")]
            public virtual Ranorex.Text TxtGeneric8
            {
                get
                {
                    return _txtgeneric8Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric8 item info.
            /// </summary>
            [RepositoryItemInfo("5db4037a-0983-4032-b8b4-9788d5d330b7")]
            public virtual RepoItemInfo TxtGeneric8Info
            {
                get
                {
                    return _txtgeneric8Info;
                }
            }

            /// <summary>
            /// The TxtGeneric9 item.
            /// </summary>
            [RepositoryItem("747327fd-4b6c-483e-a202-fb67e90426d8")]
            public virtual Ranorex.Text TxtGeneric9
            {
                get
                {
                    return _txtgeneric9Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric9 item info.
            /// </summary>
            [RepositoryItemInfo("747327fd-4b6c-483e-a202-fb67e90426d8")]
            public virtual RepoItemInfo TxtGeneric9Info
            {
                get
                {
                    return _txtgeneric9Info;
                }
            }

            /// <summary>
            /// The TxtGeneric10 item.
            /// </summary>
            [RepositoryItem("60333416-8525-42cf-aab8-1111878cf713")]
            public virtual Ranorex.Text TxtGeneric10
            {
                get
                {
                    return _txtgeneric10Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtGeneric10 item info.
            /// </summary>
            [RepositoryItemInfo("60333416-8525-42cf-aab8-1111878cf713")]
            public virtual RepoItemInfo TxtGeneric10Info
            {
                get
                {
                    return _txtgeneric10Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
